tips/urls.py
from django.conf.urls.defaults import *
from tips.feeds import LatestTipFeed

urlpatterns = patterns('',
    url(r'^$', 'tips.views.show_latest', name='tip-latest'),    
    url(r'^mytips/$', 'tips.views.mytips', name='tip-mytips'),
    url(r'^read/(?P<id>.+)/(?P<slug>[a-zA-Z0-9_.-]+)/$', 'tips.views.read_more', name='tip-read'),
    url(r'^edit/(?P<id>.+)/$', 'tips.views.show_edit_form', name='tip-edit'),
    url(r'^delete/(?P<id>.+)/$', 'tips.views.delete_tip', name='tip-delete'),
    url(r'^add/$', 'tips.views.add_tip', name='tip-add'),
    url(r'^update/$', 'tips.views.update_tip', name='tip-update'),
    url(r'^by/(?P<slug>[a-zA-Z0-9_.-]+)/$', 'tips.views.by_tag', name='tips-by-tag'),
    url(r'^search/$', 'tips.views.simple_search', name='tip-simple-search'),
    url(r'^rate/(?P<id>.+)/$', 'tips.views.rate_tip', name='tip-rate'),
    url(r'^bookmark/(?P<id>.+)/$', 'tips.views.bookmark_tip', name='tip-bookmark'),
    url(r'^feed/$', LatestTipFeed(), name='tip-feed'),

)

urls.py
from django.conf.urls.defaults import *
from tips.sitemaps import LatestTipSitemap

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Example:
    # (r'^tipsforlinux/', include('tipsforlinux.foo.urls')),

    # Uncomment the admin/doc line below and add 'django.contrib.admindocs' 
    # to INSTALLED_APPS to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)),
    (r'^comments/', include('django.contrib.comments.urls')),
    (r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': {'tips':LatestTipSitemap}}),
    (r'^robots\.txt$', include('robots.urls')),

    #(r'^$', 'socialauth.views.signin_complete'),
    (r'^$', 'tips.views.show_latest'),
    (r'^accounts/', include('socialauth.urls')),
    (r'^tips/', include('tips.urls')),
    (r'^contact/', include('contact_form.urls')),
)

from django.conf import settings
if settings.LOCAL:

    urlpatterns += patterns('',
        # This is for the CSS and static files:
        (r'^media/(?P<path>.*)$', 'django.views.static.serve',
         {'document_root': settings.MEDIA_ROOT}),
    )

tips/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User
from django.db.models import signals
from django.template.defaultfilters import slugify
from django.conf import settings

from middleware import threadlocals

from tagging.fields import TagField
from tagging.models import Tag


class Tip(models.Model):
    author = models.ForeignKey(User, editable=False, default=threadlocals.get_current_user) 
    title = models.CharField(max_length=50)
    slug_title = models.SlugField(max_length=150, blank=True, null=True)
    body = models.TextField()
    pub_date = models.DateField(auto_now_add=True)
    is_public = models.BooleanField(default=True)
    approved = models.BooleanField(default=False)
    enable_comments = models.BooleanField(default=True)
    hits = models.IntegerField(default=0)
    tags = TagField()
    
    class Meta:
        ordering = ('-id', '-pub_date',)
    
    def __unicode__(self):
        return self.title
        
    def get_absolute_url(self):
        return '/tips/read/%d/%s' % (self.id, self.slug_title)
    
    def set_tags(self, tags):
        Tag.objects.update_tags(self, tags)

    def get_tags(self):
        return Tag.objects.get_for_object(self)    

 
def tip_pre_save(signal, instance, sender, **kwargs):
    #if not instance.slug_title:
    slug = slugify(instance.title)
    new_slug = slug
    counter = 0

    while Tip.objects.filter(slug_title=new_slug).exclude(id=instance.id).count() > 0:
        counter += 1
        new_slug = '%s-%d'%(slug, counter)

    instance.slug_title = new_slug
signals.pre_save.connect(tip_pre_save, sender=Tip)
    

class Bookmark(models.Model):
    user = models.ForeignKey(User)
    tip = models.ForeignKey(Tip)
    mark_date = models.DateField(auto_now_add=True)
    
    def __unicode__(self):
        return u'%s by %s (bookmarked in %s)' % (self.tip, self.user, self.mark_date)


class Rating(models.Model):
    user = models.ForeignKey(User)
    tip = models.ForeignKey(Tip)
    useful = models.BooleanField(default=True)
    
    def __unicode__(self):
        return u'%s' % self.useful
    
    def get_rating(self):
        if self.useful:
            return u'useful'
        return u'not useful'

tips/forms.py
# -*- coding: utf-8 -*-
from django.forms.models import ModelForm
from django.forms import forms
from django.conf import settings
from django.forms.widgets import TextInput
from django.utils import simplejson
from django.utils.safestring import mark_safe
from django.forms.widgets import HiddenInput
from django.forms.fields import IntegerField
from django.core.mail import EmailMessage

from tagging.forms import TagField
from tagging.models import Tag
from tips.models import Tip


class AutoCompleteTagInput(TextInput):
    
    class Media:
        css = {
            'all': ('%s/js/jquery/jquery.autocomplete.css' % settings.MEDIA_URL,)
        }
        js = (
            '%s/js/jquery.js' % settings.MEDIA_URL,
            '%s/js/jquery/lib/jquery.bgiframe.min.js' % settings.MEDIA_URL,
            '%s/js/jquery/lib/jquery.ajaxQueue.js' % settings.MEDIA_URL,
            '%s/js/jquery/jquery.autocomplete.js' % settings.MEDIA_URL
        )

    def render(self, name, value, attrs=None):
        output = super(AutoCompleteTagInput, self).render(name, value, attrs)
        #page_tags = Tag.objects.usage_for_model(Lancamento)
        page_tags = Tag.objects.all()
        tag_list = simplejson.dumps([tag.name for tag in page_tags],
                                    ensure_ascii=False)
        return output + mark_safe(u'''<script type="text/javascript">
            jQuery("#id_%s").autocomplete(%s, {
                width: 150,
                max: 10,
                highlight: false,
                multiple: true,
                multipleSeparator: ", ",
                scroll: true,
                scrollHeight: 300,
                matchContains: true,
                autoFill: true,
                });
            </script>''' % (name, tag_list))


class TipForm(ModelForm):
    id = IntegerField(required=False, widget=HiddenInput())
    tags = TagField(max_length=50, label='Tags', required=False, widget=AutoCompleteTagInput())
    
    class Meta:
        model = Tip
        exclude = ['author', 'slug_title', 'pub_date', 'hits', 'approved']
        
    def __init__(self, *args, **kwargs):
        super(TipForm, self).__init__(*args, **kwargs)
        if self.instance.id:
            self.initial['tags'] = ' '.join([item.name for item in Tag.objects.get_for_object(self.instance)])
    
    def save(self, *args, **kwargs):        
        self.instance.approved = settings.APPROVE_NEW_TIPS_AUTOMATICALY
        super(TipForm, self).save(*args, **kwargs)
        
        from_email = settings.DEFAULT_FROM_EMAIL
        recipient_list = [mail_tuple[1] for mail_tuple in settings.ADMINS]
        
        subject = '[TIP] %s' % self.instance.slug_title
        message = "Author: %s \nE-mail: %s\n\n%s\n\n%s" % (self.instance.author, self.instance.author.email, self.instance.title, self.instance.body)
        mail = EmailMessage(subject, message, from_email, recipient_list)
        try:
            mail.send()
        except:
            pass

tips/views.py
# -*- coding: utf-8 -*-
from django.contrib.auth.decorators import login_required
from django.views.generic.simple import direct_to_template
from django.contrib.comments.views.comments import post_comment
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.shortcuts import get_object_or_404, get_list_or_404
from django.http import Http404

from tagging.models import Tag, TaggedItem
from tips.forms import TipForm
from tips.models import Tip, Bookmark

        

def _show_tips_in_home(request, tips=None, tag=None):
    if tips is None:
        tips = Tip.objects.filter(is_public=True, approved=True)
    
    if not tag is None:
        tips = TaggedItem.objects.get_by_model(tips, tag)
    
    context = {'tips': tips, 'active_menu':'home'}
    return direct_to_template(request, 'index.html', context)
    

def show_latest(request):
    return _show_tips_in_home(request)


def by_tag(request, slug):
    try:
        tag = Tag.objects.get(slug=slug)
        return _show_tips_in_home(request, None, tag)
    except:
        raise Http404
        

def read_more(request, id, slug=None):
    tip = get_object_or_404(Tip, pk=id)
    
    if not tip.author == request.user:
        tip.hits += 1
        tip.save()
    
    context = {'tip': tip, 'active_menu':'home'}
    try:
        rating = tip.rating_set.get(user=request.user)
        context.update({'rating': rating})
    except:
        pass
        
    try:
        bookmark = tip.bookmark_set.get(user=request.user)
        context.update({'bookmark': bookmark})
    except:
        pass
    
    return direct_to_template(request, 'read.html', context)


def simple_search(request):
    if 'text' in request.GET:
        text = request.GET['text']
        
        tips = Tip.objects.filter(Q(title__icontains=text) | Q(body__icontains=text))
        return _show_tips_in_home(request, tips, None)
    
    return HttpResponseRedirect(reverse('tip-latest'))


@login_required
def mytips(request, form=None):
    if form == None:
        form = TipForm()
    tips = Tip.objects.filter(author=request.user)
    bookmarked_tips = Bookmark.objects.filter(user=request.user)
    
    context = {'tips':tips, 'bookmarked_tips': bookmarked_tips, 'form': form, 'active_menu':'mytips'}
    return direct_to_template(request, 'mytips.html', context)


@login_required
def add_tip(request):
    if request.POST:
        form = TipForm(request.POST)
        try:
            form.save()
            return HttpResponseRedirect(reverse('tip-mytips'))
        except:
            pass
            
        return mytips(request, form)
    return HttpResponseRedirect(reverse('tip-mytips'))


@login_required
def delete_tip(request, id):
    tip = get_object_or_404(Tip, id=id, author=request.user)
    tip.delete()
    return HttpResponseRedirect(reverse('tip-mytips'))


@login_required
def show_edit_form(request, id, slug=None):
    tip = get_object_or_404(Tip, id=id, author=request.user)
    context = {'form': TipForm(instance=tip), 'active_menu':'mytips'}
    return direct_to_template(request, 'edit.html', context)


@login_required
def update_tip(request):
    if request.POST:
        id = request.POST.get('id')
        tip = get_object_or_404(Tip, id=id, author=request.user)
        form = TipForm(request.POST, instance=tip)
        try:
            form.save()
            return HttpResponseRedirect(reverse('tip-mytips'))
        except:
            pass
            
    context = {'form':form , 'active_menu':'mytips'}
    return direct_to_template(request, 'edit.html', context)


@login_required
def rate_tip(request, id):
    if 'score' in request.GET:
        is_useful = (request.GET.get('score') == 'up')
        tip = get_object_or_404(Tip, id=id)
        
        if not request.user == tip.author:
            try:
                rating = tip.rating_set.get(user=request.user)
                rating.useful = is_useful
                rating.save()
            except:
                rating = tip.rating_set.create(user=request.user, useful=is_useful)
            
            try:
                if '/tips/read/' in request.META['HTTP_REFERER']:
                    return HttpResponseRedirect(request.META['HTTP_REFERER'])
            except:
                pass
            
    return HttpResponseRedirect(reverse('tip-mytips'))


@login_required
def bookmark_tip(request, id):
    if 'action' in request.GET:
        tip = get_object_or_404(Tip, pk=id)
        
        if not request.user == tip.author:
            action = request.GET.get('action')
            if action == 'add':
                bookmarked_tip = tip.bookmark_set.get_or_create(user=request.user)
                
            elif action == 'delete':
                try:
                    bookmarked_tip = tip.bookmark_set.get(user=request.user)
                    bookmarked_tip.delete()
                except:
                    pass

            try:
                if '/tips/read/' in request.META['HTTP_REFERER']:
                    return HttpResponseRedirect(request.META['HTTP_REFERER'])
            except:
                pass

    return HttpResponseRedirect(reverse('tip-mytips'))

templates/mobile/tips/edit.html
{% extends 'base_site.html' %}

{% block main %}

<div class="info">
  <h1>Edit Tip</h1>
</div>

<form id="formTipEdit" name="formTipEdit" action="{% url tip-update %}" method="post" class="genericform">
    {% include 'form.html' %}
    
    <div>
        <input type="submit" value="Save" class="button">
        <input type="button" value="Cancel" class="button" onclick="history.go(-1);">
    </div>

</form>

{% endblock %}

templates/mobile/tips/form.html
{% csrf_token %} 

{{ form.id }}
<label class="title" for="id_title" accesskey="t">Title</label> {{ form.title }} <span class="errormessage">{{ form.title.errors }}</span>
<label class="title" for="id_body" accesskey="b">Tip</label> {{ form.body }} <span class="errormessage">{{ form.body.errors }}</span>
<label class="title" for="id_tags" accesskey="d">Tags</label> {{ form.tags }} <span class="errormessage">{{ form.tags.errors }}</span>
<label class="title" ></label>{{ form.is_public }}<label class="desc" for="id_is_public"> Is public?</label>
<label class="title" ></label>{{ form.enable_comments }}<label class="desc" for="id_enable_comments"> Enable comments?</label>
<p class="terms">Attention: Your tip may be rejected if it is considered improper or duplicate by Administrator.</p>

templates/mobile/tips/index.html
{% extends "base_site.html" %}

{% block main %}

{% load truncate %}

{% if not tips %}
<div id="error404">
    <img src="{{ MEDIA_URL }}css/images/sadpenguin.png" width="150" height="137" alt="Sad penguin"/>
    <p>Sorry, no tips found.</p>
</div>
{% endif %}

{% load pagination_tags %}
{% autopaginate tips 10 %}


<ul class="list_data">
{% for tip in tips %}
   <li>
       <a href="{{ tip.get_absolute_url }}" title="{{ tip.title }}">
           {% include 'post_title.html' %}
           <span class="description">{{ tip.body|striptags|truncate:100|removetags:"div b span a p br table"|safe }}</span>
       </a>
       <br class="clear"/>
   </li>
<!--
    {% if tip.body|striptags|truncate:100|length > 100 %}
        <div class="post-footer reply">
            <a href="{{ tip.get_absolute_url }}" class="button">keep reading...</a>
        </div>
    {% endif %}
-->
{% endfor %}
</ul>

<br class="clear"/>

{% paginate %}


{% endblock %}

templates/mobile/tips/mytips.html
{% extends 'base_site.html' %}

{% block main %}

{% load pagination_tags %}

{% autopaginate tips 10 %}

<div class="tips">
    <div class="info"><h1>My Tips</h1></div>

    {% if tips %}
        {% paginate %}
        <table cellpadding="0" cellspacing="0" border="1">
            <thead>
                <td width="80">Posted in</td>
                <td width="400">Title</td>
                <td class="center">Hits</td>
                <td class="center">Approved?</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
            </thead>
            <tbody>
            {% for tip in tips %}
                <tr style="background:{% cycle '#ffffff' '#f8f8f8' %}">
                    <td>{{ tip.pub_date }}</td>
                    <td><a href="{{ tip.get_absolute_url }}">{{ tip.title }}</a></td>
                    <td class="center">{{ tip.hits }}</td>
                    <td class="center" style="color:{% if tip.approved %}green{% else %}red{% endif %}">{{ tip.approved|yesno }}</td>
                    <td><a href="{% url tip-edit tip.id %}" title="Edit"><div class="edit"></div><noscript>Edit</noscript></a></td>
                    <td><a href="{% url tip-delete tip.id %}" title="Delete"><div class="delete"></div><noscript>Delete</noscript></a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

    {% else %}
        <p style="font-size:0.8em">No tips.</p>
    {% endif %}

</div>

<br><br>

{% autopaginate bookmarked_tips 10 %}

<div class="tips">
    <div class="info"><h1>Bookmarked Tips</h1></div>

    {% if bookmarked_tips %}
        <table cellpadding="0" cellspacing="0" border="1">
            <thead>
                <td width="80">Posted in</td>
                <td width="400">Title</td>
                <td width="150" class="center">Author</td>
                <td>&nbsp;</td>
            </thead>
            <tbody>
            {% for b in bookmarked_tips %}
                <tr style="background:{% cycle '#ffffff' '#f8f8f8' %}">
                    <td>{{ b.tip.pub_date }}</td>
                    <td><a href="{{ b.tip.get_absolute_url }}">{{ b.tip.title }}</a></td>
                    <td class="center">{{ b.tip.author }}</td>
                    <td><a href="{% url tip-bookmark b.tip.id %}?action=delete" title="Delete"><div class="delete"></div><noscript>Delete</noscript></a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        {% paginate %}
        
    {% else %}
        <p style="font-size:0.8em">No bookmarked tips. You can't add on bookmark yourself tips.</p>
    {% endif %}

</div>

<br><br>

<div class="info">
  <h1>New Tip</h1>
  <div></div>
</div>

<form id="formTipAdd" name="formTipAdd" action="{% url tip-add %}" method="post" class="genericform">
    {% include 'form.html' %}

    <div>
        <input type="submit" value="Add" class="button">
    </div>

</form>

{% endblock %}

templates/mobile/tips/post_title.html
{% load truncate %}

    <span class="header">
        {{ tip.title|upper|truncate:47 }}
    </span><br/>
    
<!--

<h1 class="post-title"><a href="{{ tip.get_absolute_url }}" title="{{ tip.title }}"><strong>{{ tip.title|upper|truncate:47 }}</strong></a></h1>
<h2 class="post-header-line1">{{ tip.pub_date|date:"F j, Y" }} by {{ tip.author }} {% if tip.get_tags %}| {{ tip.get_tags|safeseq|join:", " }} {% endif %}</h2>

{% ifequal request.user tip.author  %}
    <a href="{% url tip-edit tip.id %}" title="Edit"><div class="edit" style="float:left;margin-right:5px;"></div><noscript>Edit</noscript></a>
    <a href="{% url tip-delete tip.id %}" title="Delete"><div class="delete" style="float:left;"></div><noscript>Delete</noscript></a>
    <br/>
{% endifequal %}
-->

templates/mobile/tips/read.html
{% extends 'base_site.html' %}

{% load comments %}
{% load gravatar %}
{% load truncate %}

{% block meta_keywords %}{{ tip.title }}{% endblock %}

{% block title %}
  {{ block.super }} - {{ tip.title|lower }}
{% endblock %}

{% block main %}
<div class="inner">
    <h2 class="header">{{ tip.title|upper|truncate:47 }}</h2>
    <p>
        {{ tip.body|striptags|linebreaksbr|safe }}
    </p>
</div>

<br class="clear"/><br/>

<ul class="list_data">
    {% get_comment_list for tip as comment_list %}
    {% for comment in comment_list %}
    <li>
        <span class="avatar">
            {% gravatar comment.user_email 48 %}
        </span>
        <span class="header with_avatar">{{ comment.name }} says</span><br/>
        <span class="description">{{ comment.comment|linebreaks }}</span>
        <br class="clear"/>
    </li>
    {% endfor %}
</ul>

{% endblock %}